/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

Hey Dhanno
 */

package reversiechess;

import java.util.Scanner;
import java.awt.Color;
import java.awt.Component;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ram
 */
public class ChessBoard extends javax.swing.JFrame {

    /**
     * Creates new form ChessBoard
     */
    public ChessBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBBishop1 = new javax.swing.JLabel();
        jBBishop2 = new javax.swing.JLabel();
        jWKnight1 = new javax.swing.JLabel();
        jWBishop2 = new javax.swing.JLabel();
        jWBishop1 = new javax.swing.JLabel();
        jWKnight2 = new javax.swing.JLabel();
        jBKnight2 = new javax.swing.JLabel();
        jBKnight1 = new javax.swing.JLabel();
        jBKing = new javax.swing.JLabel();
        jWKing = new javax.swing.JLabel();
        jWRook1 = new javax.swing.JLabel();
        jWRook2 = new javax.swing.JLabel();
        jBRook2 = new javax.swing.JLabel();
        jBRook1 = new javax.swing.JLabel();
        jWQueen = new javax.swing.JLabel();
        jBQueen = new javax.swing.JLabel();
        jWPawn1 = new javax.swing.JLabel();
        jWPawn2 = new javax.swing.JLabel();
        jWPawn3 = new javax.swing.JLabel();
        jWPawn5 = new javax.swing.JLabel();
        jWPawn4 = new javax.swing.JLabel();
        jWPawn6 = new javax.swing.JLabel();
        jBPawn8 = new javax.swing.JLabel();
        jWPawn7 = new javax.swing.JLabel();
        jWPawn8 = new javax.swing.JLabel();
        jBPawn1 = new javax.swing.JLabel();
        jBPawn2 = new javax.swing.JLabel();
        jBPawn3 = new javax.swing.JLabel();
        jBPawn4 = new javax.swing.JLabel();
        jBPawn5 = new javax.swing.JLabel();
        jBPawn7 = new javax.swing.JLabel();
        jBPawn6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jChessBoard = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer ren,int row,int col){
                Component comp=super.prepareRenderer(ren,row,col);
                int total=row+col;
                if (total%2==0 || total==0)
                comp.setBackground(Color.WHITE);
                else
                comp.setBackground(new Color(51,153,255));
                return comp;
            }
        };
        jWoodenTexture = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reversie Chess");
        setMinimumSize(new java.awt.Dimension(1650, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        jBBishop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_bdt60.png"))); // NOI18N
        getContentPane().add(jBBishop1);
        jBBishop1.setBounds(380, 140, 60, 60);

        jBBishop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_bdt60.png"))); // NOI18N
        getContentPane().add(jBBishop2);
        jBBishop2.setBounds(570, 140, 60, 60);

        jWKnight1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_nlt60.png"))); // NOI18N
        getContentPane().add(jWKnight1);
        jWKnight1.setBounds(320, 580, 60, 70);

        jWBishop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_blt60.png"))); // NOI18N
        getContentPane().add(jWBishop2);
        jWBishop2.setBounds(570, 580, 60, 70);

        jWBishop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_blt60.png"))); // NOI18N
        getContentPane().add(jWBishop1);
        jWBishop1.setBounds(380, 580, 60, 70);

        jWKnight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_nlt60.png"))); // NOI18N
        getContentPane().add(jWKnight2);
        jWKnight2.setBounds(630, 580, 60, 70);

        jBKnight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_ndt60.png"))); // NOI18N
        getContentPane().add(jBKnight2);
        jBKnight2.setBounds(630, 130, 60, 70);

        jBKnight1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_ndt60.png"))); // NOI18N
        getContentPane().add(jBKnight1);
        jBKnight1.setBounds(320, 130, 60, 70);

        jBKing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_kdt60.png"))); // NOI18N
        getContentPane().add(jBKing);
        jBKing.setBounds(500, 140, 60, 60);

        jWKing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_klt60.png"))); // NOI18N
        getContentPane().add(jWKing);
        jWKing.setBounds(510, 580, 60, 70);

        jWRook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_rlt60.png"))); // NOI18N
        jWRook1.setText("jLabel1");
        getContentPane().add(jWRook1);
        jWRook1.setBounds(260, 580, 60, 70);

        jWRook2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_rlt60.png"))); // NOI18N
        jWRook2.setText(" ");
        getContentPane().add(jWRook2);
        jWRook2.setBounds(690, 580, 60, 70);

        jBRook2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_rdt60.png"))); // NOI18N
        getContentPane().add(jBRook2);
        jBRook2.setBounds(690, 140, 60, 60);

        jBRook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_rdt60.png"))); // NOI18N
        jBRook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRook1MouseClicked(evt);
            }
        });
        getContentPane().add(jBRook1);
        jBRook1.setBounds(260, 140, 60, 60);

        jWQueen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_qlt60.png"))); // NOI18N
        getContentPane().add(jWQueen);
        jWQueen.setBounds(440, 580, 60, 70);

        jBQueen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_qdt60.png"))); // NOI18N
        getContentPane().add(jBQueen);
        jBQueen.setBounds(440, 140, 60, 60);

        jWPawn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        jWPawn1.setText(" ");
        getContentPane().add(jWPawn1);
        jWPawn1.setBounds(260, 520, 60, 60);

        jWPawn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        getContentPane().add(jWPawn2);
        jWPawn2.setBounds(690, 520, 60, 60);

        jWPawn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        getContentPane().add(jWPawn3);
        jWPawn3.setBounds(630, 520, 60, 60);

        jWPawn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        getContentPane().add(jWPawn5);
        jWPawn5.setBounds(510, 520, 60, 60);

        jWPawn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        getContentPane().add(jWPawn4);
        jWPawn4.setBounds(570, 520, 60, 60);

        jWPawn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        getContentPane().add(jWPawn6);
        jWPawn6.setBounds(320, 520, 60, 60);

        jBPawn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn8);
        jBPawn8.setBounds(690, 200, 60, 60);

        jWPawn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        getContentPane().add(jWPawn7);
        jWPawn7.setBounds(380, 520, 60, 60);

        jWPawn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_plt60.png"))); // NOI18N
        getContentPane().add(jWPawn8);
        jWPawn8.setBounds(440, 520, 60, 60);

        jBPawn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn1);
        jBPawn1.setBounds(260, 200, 60, 60);

        jBPawn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn2);
        jBPawn2.setBounds(320, 200, 60, 60);

        jBPawn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn3);
        jBPawn3.setBounds(380, 200, 60, 60);

        jBPawn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn4);
        jBPawn4.setBounds(440, 200, 60, 60);

        jBPawn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn5);
        jBPawn5.setBounds(500, 200, 60, 60);

        jBPawn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn7);
        jBPawn7.setBounds(630, 200, 60, 60);

        jBPawn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/Chess_pdt60.png"))); // NOI18N
        getContentPane().add(jBPawn6);
        jBPawn6.setBounds(570, 200, 60, 60);

        jChessBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G", "H"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jChessBoard.setRowHeight(64);
        jScrollPane1.setViewportView(jChessBoard);
        if (jChessBoard.getColumnModel().getColumnCount() > 0) {
            jChessBoard.getColumnModel().getColumn(0).setResizable(false);
            jChessBoard.getColumnModel().getColumn(1).setResizable(false);
            jChessBoard.getColumnModel().getColumn(2).setResizable(false);
            jChessBoard.getColumnModel().getColumn(3).setResizable(false);
            jChessBoard.getColumnModel().getColumn(4).setResizable(false);
            jChessBoard.getColumnModel().getColumn(5).setResizable(false);
            jChessBoard.getColumnModel().getColumn(6).setResizable(false);
            jChessBoard.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 110, 492, 545);

        jWoodenTexture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reversiechess/fd8fcec8cfb61a5640d95f11a82eb4c0.png"))); // NOI18N
        jWoodenTexture.setText("jLabel2");
        jWoodenTexture.setAlignmentX(10.0F);
        jWoodenTexture.setAlignmentY(5.0F);
        getContentPane().add(jWoodenTexture);
        jWoodenTexture.setBounds(0, 0, 1000, 870);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(840, 280, 71, 21);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 320, 71, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRook1MouseClicked
jChessBoard = new javax.swing.JTable(){
    int x = jChessBoard.getSelectedRow();
    int y = jChessBoard.getSelectedColumn();
    
    public Component prepareRenderer(TableCellRenderer ren,int row,int col){
        Component comp=super.prepareRenderer(ren,row,col);
        
        if ((row==x || col==y) && !(row==x && col==y))
        
        comp.setBackground(Color.red);
//        comp.setBackground(new Color(51,153,255));
        return comp;
    }
};        // TODO add your handling code here:
    }//GEN-LAST:event_jBRook1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChessBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBBishop1;
    private javax.swing.JLabel jBBishop2;
    private javax.swing.JLabel jBKing;
    private javax.swing.JLabel jBKnight1;
    private javax.swing.JLabel jBKnight2;
    private javax.swing.JLabel jBPawn1;
    private javax.swing.JLabel jBPawn2;
    private javax.swing.JLabel jBPawn3;
    private javax.swing.JLabel jBPawn4;
    private javax.swing.JLabel jBPawn5;
    private javax.swing.JLabel jBPawn6;
    private javax.swing.JLabel jBPawn7;
    private javax.swing.JLabel jBPawn8;
    private javax.swing.JLabel jBQueen;
    private javax.swing.JLabel jBRook1;
    private javax.swing.JLabel jBRook2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jChessBoard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jWBishop1;
    private javax.swing.JLabel jWBishop2;
    private javax.swing.JLabel jWKing;
    private javax.swing.JLabel jWKnight1;
    private javax.swing.JLabel jWKnight2;
    private javax.swing.JLabel jWPawn1;
    private javax.swing.JLabel jWPawn2;
    private javax.swing.JLabel jWPawn3;
    private javax.swing.JLabel jWPawn4;
    private javax.swing.JLabel jWPawn5;
    private javax.swing.JLabel jWPawn6;
    private javax.swing.JLabel jWPawn7;
    private javax.swing.JLabel jWPawn8;
    private javax.swing.JLabel jWQueen;
    private javax.swing.JLabel jWRook1;
    private javax.swing.JLabel jWRook2;
    private javax.swing.JLabel jWoodenTexture;
    // End of variables declaration//GEN-END:variables
}
